apiVersion: v1
kind: ConfigMap
metadata:
  name: cms0-config
  labels:
    app.kubernetes.io/name: cms0
data:
  INSTANCE_DOMAIN: 'api.topia.io'
  INSTANCE_PROTOCOL: 'https'
  INTERACTIVE_KEY: 'FlJkKX5U50AXxkvVV73G'
  NODE_ENV: 'production'
  PORT: '3000'
